# Generated by Django 2.1.12 on 2019-09-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_auto_20180130_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralresponse',
            name='ip_address',
            field=models.CharField(max_length=265),
        ),
    ]
