# Generated by Django 4.2.13 on 2024-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referrals", "0003_auto_20190918_1831"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralresponse",
            name="http_referrer",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
